
const ReportFilterConst = {
    IS_TEST:                'IS_TEST',
    SELECT_LOADED:          'SELECT_LOADED',
    SELECT_SELECTED:        'SELECT_SELECTED',
    UPDATE_SELECTS:         'UPDATE_SELECTS',
    FILTER_REQUEST:         'FILTER_REQUEST',

    SET_ALL_PAYMENTS:       'SET_ALL_PAYMENTS',
    SET_PAYMENTS_COUNT:     'SET_PAYMENTS_COUNT',
    REPORT_LINK:            'REPORT_LINK',
    SHOW_HIDE_LOADER:       'SHOW_HIDE_LOADER',
    SET_CLEAR_DOWNLOAD:     'SET_CLEAR_DOWNLOAD',

    MERCHANT_SORT:          'MERCHANT_SORT',
    MERCHANT_POINT_SORT:    'MERCHANT_POINT_SORT'
};

export default ReportFilterConst;